# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_auto_20150925_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organ', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cancer5yrSurvivalRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('percentaje', models.FloatField()),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.Cancer')),
            ],
        ),
        migrations.CreateModel(
            name='CancerAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_es', models.CharField(max_length=100)),
                ('exposition_in', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CancerAgentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.CancerAgent')),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.Cancer')),
            ],
        ),
    ]
