# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0005_auto_20160115_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancer',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='organ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canceragent',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
