# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0006_auto_20160115_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancer',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='canceragent',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
