# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0007_auto_20160121_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canceragent',
            name='exposition_in',
        ),
    ]
